title: Publishing to GitHub Pages: Starter Pack
description: Final documentation project made as part of Technical Communication studies at Vistula University.
theme: just-the-docs

url: https://beaskoczy.github.io/githubpages-publication/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_schene: dark

heading_anchors: true

# Navigation links
  aux_links:
    "View on GitHub":
        - "https://github.com/beaskoczy/githubpages-publication"


